const Colors = {
  red: "#be1622",
  lightRed: "#fff1f6",
  orange: "#FF3B00",
  green: "#02c24d",
  hardGreen: "#02c24d",
  lightGreen: "#D8F7E7",
  black: "#333333",
  yellow: "#FDB85E",
  paleGray: "#FAFAFA",
  lightGray: "#F5F5F5",
  silver: "#555555",
  mediumGray: "#E1E1E1",
  darkGray: "#ACACAC",
  lightBlue: "#0066cc",
  blue: "#191970",
  arcticBlue: "#f1f1ff",
  white: "#FFFFFF",
  transparent: "#00000000",
  line: "#00C300",
  gray: "#D1D1D1",
  lightOrange: "#f6e6e1",
};

export const ColorSet = {
  primary: Colors.blue,
  secondary: Colors.orange,
  info: Colors.lightBlue,
  success: Colors.green,
  warning: Colors.yellow,
  danger: Colors.red,
  error: Colors.red,
  disabled: Colors.gray,
  background: Colors.lightGray,
  outline: Colors.mediumGray,
  black: Colors.black,
  white: Colors.white,
  transparent: Colors.transparent,
};
